(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(apropos-do-all t)
 '(column-number-mode t)
 '(cua-mode t)
 '(delete-selection-mode t)
 '(desktop-load-locked-desktop 'check-pid)
 '(desktop-save-mode t)
 '(diff-switches "-u")
 '(display-fill-column-indicator nil)
 '(fill-column 80)
 '(font-use-system-font t)
 '(fringe-mode '(nil . 0) nil (fringe))
 '(global-display-fill-column-indicator-mode nil)
 '(global-display-line-numbers-mode t)
 '(global-hl-line-mode t)
 '(global-tab-line-mode t)
 '(highlight-nonselected-windows nil)
 '(ibuffer-always-show-last-buffer :nomini)
 '(ibuffer-default-shrink-to-minimum-size nil)
 '(ibuffer-default-sorting-mode 'major-mode)
 '(ibuffer-jump-offer-only-visible-buffers t)
 '(ibuffer-movement-cycle t)
 '(ibuffer-old-time 8)
 '(ibuffer-show-empty-filter-groups nil)
 '(ibuffer-use-other-window nil)
 '(imenu-auto-rescan t)
 '(imenu-max-items 42)
 '(imenu-sort-function 'imenu--sort-by-name)
 '(indicate-empty-lines t)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(magit-delta-hide-plus-minus-markers t)
 '(mode-line-compact t)
 '(mouse-yank-at-point nil)
 '(org-agenda-files "agenda_files")
 '(org-directory "/home/org")
 '(org-log-done 'note)
 '(package-selected-packages '(xterm-color symbol-overlay markdown-mode))
 '(require-final-newline t)
 '(ring-bell-function 'ignore)
 '(save-place-mode t)
 '(scroll-bar-mode 'left)
 '(sh-basic-offset 2)
 '(sh-indent-for-case-alt '+)
 '(size-indication-mode t)
 '(tab-bar-close-tab-select 'left)
 '(tab-bar-format
   '(tab-bar-format-history tab-bar-format-tabs tab-bar-separator tab-bar-format-add-tab))
 '(tab-bar-history-mode t)
 '(tab-bar-mode t)
 '(tab-bar-new-tab-choice t)
 '(tab-bar-new-tab-group nil)
 '(tab-bar-select-tab-modifiers nil)
 '(tab-bar-tab-name-function 'tab-bar-tab-name-current)
 '(tab-line-exclude-modes '(completion-list-mode customize-mode))
 '(tab-line-switch-cycling t)
 '(tab-line-tab-name-function 'tab-line-tab-name-truncated-buffer)
 '(tab-line-tab-name-truncated-max 32)
 '(tab-line-tabs-function 'tab-line-tabs-window-buffers)
 '(tool-bar-mode nil)
 '(transient-mark-mode t)
 '(x-stretch-cursor t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cursor ((t (:background "red"))))
 '(hl-line ((t (:background "light cyan" :extend t :inherit highlight))))
 '(tab-line ((t (:height 1.0 :foreground "black" :background "gainsboro" :inherit variable-pitch)))))
