(setq fixme-modes '(emacs-lisp-mode sh-mode org-mode))
(make-face 'font-lock-fixme-face)
(make-face 'font-lock-untested-face)
(make-face 'font-lock-todo-face)
(make-face 'font-lock-caution-face)
(make-face 'font-lock-notice-face)
(mapc (lambda (mode)
        (font-lock-add-keywords
         mode
         '(("\\<\\(FIXME\\)"    1 'font-lock-fixme-face   t)
           ("\\<\\(CAUTION\\)"  1 'font-lock-caution-face t)
           ("\\<\\(UNTESTED\\)" 1 'font-lock-untested-face t)
           ("\\<\\(TODO\\)"     1 'font-lock-todo-face t)
           ("\\<\\(NOTES\\)"    1 'font-lock-notice-face  t))))
      fixme-modes)
(modify-face 'font-lock-fixme-face    "Yellow" "Red"    nil t nil nil nil nil)
(modify-face 'font-lock-caution-face  "Red"    "Yellow" nil t nil nil nil nil)
(modify-face 'font-lock-todo-face     "Green"  "Yellow" nil t nil nil nil nil)
(modify-face 'font-lock-untested-face "Blue"   "Red"    nil t nil nil nil nil)
(modify-face 'font-lock-notice-face   "Blue"   "Green"  nil t nil nil nil nil)
